/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logentries_re2_Options */

#ifndef _Included_com_logentries_re2_Options
#define _Included_com_logentries_re2_Options
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_logentries_re2_Options
 * Method:    setDefaults
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_logentries_re2_Options_setDefaults
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
