/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logentries_re2_RE2 */

#ifndef _Included_com_logentries_re2_RE2
#define _Included_com_logentries_re2_RE2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_logentries_re2_RE2
 * Method:    compileImpl
 * Signature: (Ljava/lang/String;Lcom/logentries/re2/Options;)J
 */
JNIEXPORT jlong JNICALL Java_com_logentries_re2_RE2_compileImpl
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_logentries_re2_RE2
 * Method:    releaseImpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_logentries_re2_RE2_releaseImpl
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_logentries_re2_RE2
 * Method:    fullMatchImpl
 * Signature: (Ljava/lang/String;J[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_logentries_re2_RE2_fullMatchImpl__Ljava_lang_String_2J_3Ljava_lang_Object_2
  (JNIEnv *, jclass, jstring, jlong, jobjectArray);

/*
 * Class:     com_logentries_re2_RE2
 * Method:    partialMatchImpl
 * Signature: (Ljava/lang/String;J[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_logentries_re2_RE2_partialMatchImpl__Ljava_lang_String_2J_3Ljava_lang_Object_2
  (JNIEnv *, jclass, jstring, jlong, jobjectArray);

/*
 * Class:     com_logentries_re2_RE2
 * Method:    fullMatchImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_logentries_re2_RE2_fullMatchImpl__Ljava_lang_String_2Ljava_lang_String_2_3Ljava_lang_Object_2
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

/*
 * Class:     com_logentries_re2_RE2
 * Method:    partialMatchImpl
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_logentries_re2_RE2_partialMatchImpl__Ljava_lang_String_2Ljava_lang_String_2_3Ljava_lang_Object_2
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
